2025-05-02 12:34:32.917 | INFO     | datatrove.utils.logging:add_task_logger:58 - Launching pipeline for rank=0
2025-05-02 12:34:32.918 | INFO     | datatrove.utils.logging:log_pipeline:90 - 
--- 🛠️ PIPELINE 🛠
None: None
None: None
None: None
🔻 - FILTER: 🌍 Language ID
💽 - WRITER: 🐿 Jsonl
2025-05-02 12:34:37.631 | ERROR    | datatrove.executor.base:_run_for_rank:108 - 'DocumentWrapper' object has no attribute 'id'
Traceback (most recent call last):

  File "/Users/adrienloizeau/dev/scratchGPT/data_pipeline.py", line 61, in <module>
    executor.run()
    │        └ <function LocalPipelineExecutor.run at 0x1186d5b40>
    └ <datatrove.executor.local.LocalPipelineExecutor object at 0x1186e1a20>

  File "/Users/adrienloizeau/opt/anaconda3/envs/lerobot/lib/python3.10/site-packages/datatrove/executor/local.py", line 127, in run
    stats.append(self._launch_run_for_rank(rank, ranks_q))
    │     │      │    │                    │     └ <AutoProxy[Queue] object, typeid 'Queue' at 0x1186e2b90>
    │     │      │    │                    └ 0
    │     │      │    └ <function LocalPipelineExecutor._launch_run_for_rank at 0x1186d5ab0>
    │     │      └ <datatrove.executor.local.LocalPipelineExecutor object at 0x1186e1a20>
    │     └ <method 'append' of 'list' objects>
    └ []
  File "/Users/adrienloizeau/opt/anaconda3/envs/lerobot/lib/python3.10/site-packages/datatrove/executor/local.py", line 76, in _launch_run_for_rank
    return self._run_for_rank(rank, local_rank)
           │    │             │     └ 0
           │    │             └ 0
           │    └ <function PipelineExecutor._run_for_rank at 0x1186d56c0>
           └ <datatrove.executor.local.LocalPipelineExecutor object at 0x1186e1a20>
> File "/Users/adrienloizeau/opt/anaconda3/envs/lerobot/lib/python3.10/site-packages/datatrove/executor/base.py", line 96, in _run_for_rank
    deque(pipelined_data, maxlen=0)
    │     └ <generator object DiskWriter.run at 0x1186ca180>
    └ <class 'collections.deque'>
  File "/Users/adrienloizeau/opt/anaconda3/envs/lerobot/lib/python3.10/site-packages/datatrove/pipeline/writers/disk_base.py", line 180, in run
    self.write(document, rank)
    │    │     │         └ 0
    │    │     └ <__main__.DocumentWrapper object at 0x11877cb80>
    │    └ <function DiskWriter.write at 0x11841b400>
    └ 💽 - WRITER: 🐿 Jsonl
  File "/Users/adrienloizeau/opt/anaconda3/envs/lerobot/lib/python3.10/site-packages/datatrove/pipeline/writers/disk_base.py", line 149, in write
    original_name = output_filename = self._get_output_filename(document, rank, **kwargs)
                                      │    │                    │         │       └ {}
                                      │    │                    │         └ 0
                                      │    │                    └ <__main__.DocumentWrapper object at 0x11877cb80>
                                      │    └ <function DiskWriter._get_output_filename at 0x11841b1c0>
                                      └ 💽 - WRITER: 🐿 Jsonl
  File "/Users/adrienloizeau/opt/anaconda3/envs/lerobot/lib/python3.10/site-packages/datatrove/pipeline/writers/disk_base.py", line 97, in _get_output_filename
    {"rank": str(rank).zfill(5), "id": document.id, **document.metadata, **kwargs}
                 │                     │              │        │           └ {}
                 │                     │              │        └ {'language': 'en', 'language_score': 0.9540399312973022}
                 │                     │              └ <__main__.DocumentWrapper object at 0x11877cb80>
                 │                     └ <__main__.DocumentWrapper object at 0x11877cb80>
                 └ 0

AttributeError: 'DocumentWrapper' object has no attribute 'id'
